name: 'Version reader'
description: 'Reading a version from a file, not that hard'
author: 'Simon Blomsterlund'
inputs:
  prepend: 
    required: false
    description: 'string that goes before the value'
    default: __version__=
  
  allow_feature_branches: 
    required: false
    description: 'Wether to fail if feature branch'
    default: 'false'
  
  # append: 
  #   required: false
  #   description: 'string that goes after the value'
  #   default: ''

  filename:
    required: false
    description: 'Name of the file'
    default: '__version__.py'
  
  filelocation:
    required: false
    description: 'File location relative to root, leave empty for root'
    default: ''
  
outputs:
  version:
    description: 'Version as semver string.'
runs:
  using: 'node16'
  main: 'lib/index.js'